version: '3.8'

services:
  wordpress:
    build: .                                # Builds using your local Dockerfile
    container_name: u3a_wordpress
    ports:
      - "8000:80"                           # Access WordPress at localhost:8000
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./setup.sh:/setup.sh               # Your custom setup script
    entrypoint: ["bash", "/setup.sh"]      # Override default command to run setup
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: u3a_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: u3a_phpmyadmin
    ports:
      - "8080:80"                           # Access phpMyAdmin at localhost:8080
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
