name: u3a WordPress CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for WordPress to be ready
        run: sleep 60

      - name: List Docker containers
        run: docker ps -a

      # PHP Syntax Check
      - name: PHP Lint (Syntax Check)
        run: |
          find wp-content/themes/child-theme -name "*.php" -exec php -l {} \;

      # Install and Run WordPress Coding Standards
      - name: Install PHPCS and WordPress Coding Standards
        run: |
          composer global require "squizlabs/php_codesniffer=*"
          composer global require wp-coding-standards/wpcs
          phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs

      - name: Run PHPCS on Child Theme
        run: |
          ~/.composer/vendor/bin/phpcs --standard=WordPress wp-content/themes/child-theme

      # Optional: Theme Check plugin using WP-CLI
      - name: Install WP-CLI and Theme Check
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          chmod +x wp-cli.phar
          sudo mv wp-cli.phar /usr/local/bin/wp
          wp plugin install theme-check --activate --allow-root --path=/var/www/html
          wp theme check child-theme --path=/var/www/html --allow-root || true

      - name: Tear down environment
        if: always()
        run: docker-compose -f docker-compose.yml down
