name: Deploy Child Theme to Flywp

on:
  push:
    branches: [ main ]
    paths:
      - 'wp-content/themes/child-theme/**'

jobs:
  deploy:
    name: Deploy via SFTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy child theme to Flywp via SFTP
        uses: pressidium/lftp-action@v1.0.0
        with:
          host: ${{ secrets.FLYWP_SFTP_HOST }}
          port: ${{ secrets.FLYWP_SFTP_PORT }}
          user: ${{ secrets.FLYWP_SFTP_USER }}
          pass: ${{ secrets.FLYWP_SFTP_PASS }}
          localDir: wp-content/themes/child-theme
          remoteDir: /var/www/html/wp-content/themes/child-theme
